- django_project/core/settings/project.py
- django_project/core/urls.py
Sorry @timlinux when I merge from upstream I kept the old version, I added again rosetta setting in this PR.
Thanks
> Translation support for Projecta

- django_project/changes/templates/version/detail-content.html
Hi @timlinux Now the permalink works well. Please check it. 
Thanks
> Fixes #124 | make permalink to a feature works

- deployment/docker/REQUIREMENTS.txt
- django_project/changes/templates/version/detail-content.html
- django_project/core/base_templates/admin/base_site.html
- django_project/core/settings/base.py
- django_project/core/settings/contrib.py
- django_project/core/urls.py
Hi @timlinux 
Please check this PR, I've Installed Grappelli admin and changed the Admin page title to `Projecta Admin`.
thanks
> Installing Grappelli Admin to Projecta

- .gitignore
- deployment/docker/REQUIREMENTS.txt
- django_project/core/base_templates/500.html
- django_project/core/settings/base.py
- django_project/core/settings/contrib.py
- django_project/core/settings/dev_docker.py
- django_project/core/settings/prod.py
- django_project/core/settings/project.py
- django_project/core/urls.py
- django_project/core/wsgi.py
> Clean up settings package

- deployment/sql/sponsor.sql
- deployment/sql/sponsor_in_version.sql
- deployment/sql/sponsorship_period.sql
- django_project/changes/forms.py
- django_project/changes/models/sponsor.py
- django_project/changes/models/version.py
Hi @timlinux I've removed sponsor relation in version table and in this PR I've fixed the error. Now it can running. 
refer issue #148 
Thanks
> Remove sponsor relation in version & Fixing after merging from @timlinux

- deployment/Makefile
- django_project/core/settings/base.py
- django_project/core/settings/contrib.py
- django_project/core/settings/dev.py
- django_project/core/settings/dev_docker.py
- django_project/core/settings/prod.py
- django_project/core/settings/test.py
- django_project/core/settings/test_travis.py
> Settings updates

- django_project/changes/models/sponsor.py
- django_project/changes/models/sponsorship_period.py
- django_project/changes/templates/sponsor/detail.html
- django_project/changes/templates/sponsor/list.html
- django_project/changes/views/sponsor.py
Hi @timlinux 
This is the view of sponsor list. 
But for the renewed sponsor it still on-going, I am still looking the way.
> Fixing Sponsor List 

- deployment/projecta.nginx.conf
- django_project/changes/models/entry.py
- django_project/changes/views/version.py
- django_project/core/settings/prod.py
Fix reverse proxy url change issue. Allow more domains in allowed hosts. Small formatting cleanups
> Fixes for settings

- .travis.yml
- django_project/base/migrations/0001_initial.py
- django_project/base/tests/model_factories.py
- django_project/changes/migrations/0001_initial.py
- django_project/core/model_factories.py
- django_project/core/urls.py
- django_project/vota/migrations/0001_initial.py
Hi @timlinux  Now we can run test even we still have to fix many errors test, at least it runs. 
[In travis](https://travis-ci.org/rischanlab/projecta/builds/102387694)
> Now we can run test

- django_project/core/base_templates/includes/right-nav.html
- django_project/core/base_templates/registration/logged_out.html
- django_project/core/base_templates/registration/login.html
- django_project/core/settings/project.py
- django_project/core/urls.py
Hi @timlinux I am going to merge this PR. 
This PR is about the login and logout form. 
Thanks
> Login and logout form

- django_project/base/urls.py
- django_project/base/views/__init__.py
- django_project/changes/views/version.py
Also fixes some other places where we might get 404s
> Added custom 404 hander

- django_project/changes/views/category.py
- django_project/changes/views/version.py
> Fix more 500 errors that should be giving 404's

- django_project/changes/views/category.py
- django_project/changes/views/entry.py
- django_project/changes/views/version.py
- django_project/vota/views/committee.py
Also some other tweaks for get_object views
> Fix for 500 error on invalid committee

- django_project/changes/models/sponsorship_period.py
Hi @timlinux 
I think now it solved for the tzinfo problem in [sentry](http://sentry.kartoza.com/kartoza/projecta-live/group/5848/)
In previous I was wrong to compare timezone aware datetime with naive datetime. 
Hope now it works. 
Thanks
> change datetime.now to timezone.now

- deployment/docker/REQUIREMENTS.txt
- django_project/changes/forms.py
- django_project/changes/migrations/0003_auto_20160220_0037.py
- django_project/changes/models/sponsor.py
- django_project/changes/tests/model_factories.py
- django_project/core/settings/contrib.py
> Added address support for sponsors

- django_project/changes/templates/version/detail-titles.txt
- django_project/changes/templates/version/detail.html
- django_project/changes/urls.py
- django_project/changes/views/version.py
Partial implementation for #240 - adds download of changelog as plain text gnu style page
> Added view to provide changelog as plain text.

- django_project/changes/models/version.py
> Fix for #249 - sort sponsors by date and level

- django_project/changes/templates/version/includes/version-sponsors.html
Hi @timlinux 
I've fixed the template. Please review it. I just make it fixed for the thumbnail class.
This is the screenshoot.
> Fixes #256 fixed sponsors thumbnail

- django_project/core/base_templates/includes/right-nav.html
> Add link to admin site for staff

- django_project/base/forms.py
- django_project/base/migrations/0002_project_gitter_room.py
- django_project/base/models/project.py
- django_project/base/tests/model_factories.py
- django_project/base/tests/test_models.py
- django_project/core/base_static/css/changelog.css
- django_project/core/base_templates/project_base.html
> Add gitter sidecar chat to the project project page

- django_project/core/settings/contrib.py
- django_project/core/settings/project.py
> Fix disqus chat widget

- django_project/changes/views/sponsor.py
- django_project/core/base_templates/includes/base-auth-nav-left.html
> Navigation menu to sponsors map

- django_project/changes/templates/sponsor/world-map.html
- django_project/changes/tests/test_views.py
- django_project/changes/views/sponsor.py
- django_project/core/base_static/css/changelog.css
> Sort and group sponsors by sponsorship level and add select option element

- django_project/core/base_templates/includes/base-auth-nav-left.html
> New Nav menu for the Projecta

- django_project/changes/models/version.py
- django_project/changes/tests/test_models.py
> Filter sponsors for a release by project

- deployment/docker/REQUIREMENTS.txt
Hi @dimasciput Just try this simple way. 
Please try it. 
```
#@docker-compose -p projecta run uwsgi python manage.py collectstatic --noinput
#We need to run collect static in the same context as the running
{'SMTP_1_ENV_maildomain': 'kartoza.com', 'PROJECTA_DB_PORT_5432_TCP_PORT': '5432', 'PROJECTA_DB_PORT_5432_TCP': 'tcp://172.17.0.82:5432', 'DB_ENV_USERNAME': 'docker', 'SMTP_1_ENV_smtp_user': 'noreply:docker', 'DB_PORT_5432_TCP_PORT': '5432', 'DB_PORT': 'tcp://172.17.0.82:5432', 'PROJECTA_SMTP_ENV_smtp_user': 'noreply:docker', 'DB_ENV_PASS': 'docker', 'HOME': '/root', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'PROJECTA_SMTP_NAME': '/projecta-uwsgi/projecta-smtp', 'PROJECTA_DB_PORT_5432_TCP_ADDR': '172.17.0.82', 'SMTP_ENV_smtp_user': 'noreply:docker', …
```
> Fixed error collectstatics

- django_project/core/base_templates/includes/base-auth-nav-left.html
Hi @timlinux I am going to merge this directly. 
Thanks.
> Bring back sponsor-map menu

- django_project/base/templatetags/custom_markup.py
- django_project/changes/templates/entry/includes/entry_detail.html
> Support animated gif in entry list

- django_project/core/base_templates/includes/right-nav.html
- django_project/core/base_templates/project_base.html
- django_project/core/custom_middleware.py
> Pending menu only shows items that have pending approvals

- django_project/base/templates/project/detail.html
- django_project/core/base_templates/includes/base-auth-nav-left.html
- django_project/vota/forms.py
- django_project/vota/templates/committee/list.html
- django_project/vota/tests/test_views.py
- django_project/vota/views/committee.py
> Add interface to create a team

- django_project/changes/templates/category/order.html
- django_project/changes/tests/test_views.py
- django_project/changes/views/category.py
- Add some tests
- Add a little text at the top of the page indicating that the sort order is automatically saved 
- Put a button next to the order categories title which will let the user go back to the categories management view.
> Additional function for order categories

- django_project/changes/templates/version/includes/version-list-detail.html
- django_project/core/base_static/css/changelog.css
> Fix version indent when there is no icon

- django_project/changes/templates/version/includes/version-sponsors.html
Hi @timlinux 
This PR for #328 
Previously I only made the content size static but forget to make sponsor logo in static size. 
Now it solved. 
Thanks.
> Fixes #328

- django_project/changes/templates/entry/all-pending-list.html
- django_project/changes/tests/test_views.py
- django_project/changes/urls.py
- django_project/changes/views/entry.py
- django_project/core/base_templates/includes/right-nav.html
- django_project/core/custom_middleware.py
- Added menu to open all pending entry in the project detail page
- Added test
> Add all pending entry view

- django_project/changes/templates/entry/includes/entry_detail.html
- django_project/changes/views/version.py
> Fix rst export

- django_project/base/templates/project/includes/project-panel.html
extention for : https://github.com/kartoza/projecta/pull/353
> fixing bug for image that go to detail for unapproved project

- django_project/changes/static/js/entry.js
- django_project/changes/templates/entry/detail.html
- django_project/changes/templates/entry/includes/entry_detail.html
- django_project/core/base_static/css/changelog.css
- django_project/core/base_templates/project_base.html
- django_project/core/settings/project.py
> Display thumbnail image in modal window

- django_project/changes/views/version.py
- django_project/core/base_templates/includes/right-nav.html
- django_project/core/custom_middleware.py
For this https://github.com/kartoza/projecta/pull/319
I added all pending entries approval on version detail and list view
> Add all pending entries menu in version view

- django_project/changes/static/js/category.js
- django_project/changes/templates/category/list.html
- django_project/changes/templates/category/order.html
- django_project/changes/tests/test_views.py
- django_project/changes/views/category.py
- django_project/core/base_static/css/changelog.css
- django_project/core/settings/project.py
- Fix redundant title text ( Fix #366 )
- Allow ordering from category list
> Update category list view

- django_project/core/base_static/css/fonts.css
- django_project/core/base_templates/project_base.html
Hi @timlinux 
I was thinking projecta current font is not that good, so I try to changed it with Lato font ( https://fonts.google.com/specimen/Lato ) 
Old font
New font 
What do you think?
> Change font to Lato

- django_project/core/base_templates/project_base.html
- django_project/github_issue/static/js/github-issue.js
- django_project/github_issue/urls.py
> Fixing #192

- django_project/changes/static/js/entry.js
- django_project/changes/templates/entry/includes/entry_detail.html
- django_project/changes/templates/version/detail-content.html
- django_project/changes/templates/version/detail.html
- django_project/core/base_static/css/changelog.css
- django_project/core/base_templates/project_base.html
Add sidebar for better navigation in version detail view
> Add right sidebar in version detail

- django_project/changes/templates/entry/includes/entry_detail.html
- django_project/changes/templates/version/detail-content.html
> Shows permalink button to non logged users

- django_project/base/static/css/github.css
- django_project/base/static/js/github-repo.js
- django_project/base/templates/github/populate-github.html
- django_project/base/urls.py
- django_project/base/views/github_project.py
- django_project/core/settings/contrib.py
> Ability to choose different repos from list of organizations

- deployment/docker/REQUIREMENTS.txt
- django_project/base/models/project.py
- django_project/base/tests/test_models.py
- django_project/changes/models/sponsor.py
for issue #384 
I've add unidecode to decode the special characters into normal characters for the url. Therefore, when user inputs special characters, the web won't generate errors.
> add unidecode to support unique characters from user input

- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/training_center/detail.html
> fix button style

- deployment/docker/REQUIREMENTS.txt
- django_project/certification/templates/course/detail.html
- django_project/certification/urls.py
- django_project/certification/views/certificate.py
- django_project/core/settings/contrib.py
fix #400, fix #401 and fix #430
> add print pdf certificate

- django_project/certification/templates/certificate/detail.html
- django_project/certification/views/certificate.py
> return 404 for bad id certificate

- django_project/certification/forms.py
- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/course_convener/delete.html
- django_project/certification/views/certificate.py
> use user real name instead of their username

- django_project/core/base_templates/includes/right-nav.html
- django_project/core/custom_middleware.py
> update pending menu

- django_project/certification/forms.py
- django_project/certification/migrations/0006_auto_20170615_0807.py
- django_project/certification/migrations/0007_auto_20170615_0849.py
- django_project/certification/models/attendee.py
- django_project/certification/templates/course_attendee/create.html
- django_project/certification/views/attendee.py
- django_project/certification/views/course_attendee.py
- django_project/core/settings/contrib.py
> filter attendee based on organisation

- django_project/certification/forms.py
> add type to search

- django_project/certification/static/css/custom.css
- django_project/certification/templates/certificate/detail.html
> add more info in certificate details

- django_project/core/base_templates/includes/right-nav.html
> fix pending approval navigation

- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/training_center/detail.html
fix #460 
this map can shows details in more places than the one that was already implemented.
> change map with more detailed map

- django_project/certification/migrations/0009_auto_20170710_0708.py
- django_project/certification/models/certificate.py
fix migrations for certificate
> fix migrations

- django_project/certification/static/css/organisation_detail.css
- django_project/certification/templates/certifying_organisation/delete.html
- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/course/delete.html
- django_project/certification/templates/course/detail.html
- django_project/certification/templates/course_convener/delete.html
- django_project/certification/templates/course_type/delete.html
- django_project/certification/templates/course_type/detail.html
- django_project/certification/templates/training_center/delete.html
- django_project/certification/templates/training_center/detail.html
- django_project/certification/views/course.py
- django_project/certification/views/course_type.py
- django_project/certification/views/training_center.py
- django_project/core/base_templates/includes/base-auth-nav-left.html
fix #464 and fix #465 
this PR fixes:
This navigation menu is now the same for all details view.
> fix capitalization and grammar

- .travis.yml
- django_project/certification/forms.py
- django_project/certification/views/certifying_organisation.py
- django_project/certification/views/course.py
- django_project/certification/views/course_type.py
- django_project/certification/views/training_center.py
> fix edit organisation and pending navigation

- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/course/detail.html
- django_project/certification/templates/course_type/detail.html
- django_project/certification/templates/training_center/detail.html
> remove : in summary

- .travis.yml
- django_project/certification/views/certificate.py
fix #484 
How about this @timlinux ?
> change logo size

- django_project/certification/static/js/jsi18n.js
- django_project/certification/templates/certifying_organisation/create.html
- django_project/certification/templates/certifying_organisation/list.html
- django_project/certification/templates/certifying_organisation/update.html
- django_project/certification/templates/course/detail.html
- django_project/certification/views/certifying_organisation.py
- django_project/certification/views/course.py
fix #487 
also adding `jsi18n.js` so the widget is rendered correctly for non staff user
> fix display for organisation owners who is not staff

- django_project/certification/templates/certifying_organisation/delete.html
- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/certifying_organisation/list.html
- django_project/certification/templates/certifying_organisation/pending-list.html
- django_project/certification/templates/course/delete.html
- django_project/certification/templates/course/detail.html
- django_project/certification/templates/course_attendee/delete.html
- django_project/certification/templates/course_convener/delete.html
- django_project/certification/templates/course_type/delete.html
- django_project/certification/templates/course_type/detail.html
- django_project/certification/templates/training_center/delete.html
- django_project/certification/templates/training_center/detail.html
On pending page:
Organisation details page:
Course details page:
> change button colour and add pending details

- django_project/certification/templates/certificate/validation.html
- django_project/certification/views/validate.py
Fix navigation bar in the validate certificate page
> fix navigation bar on the certificate validation page

- django_project/certification/views/certificate.py
Updates the convener and project rep titles in the report.
> Tweak wording on report template

- django_project/certification/static/css/organisation_detail.css
- django_project/certification/templates/certifying_organisation/detail.html
fix #498 and fix #503 and fix #507 
new layout:
when hover on container
> update page style

- django_project/core/settings/prod_docker.py
Hi @timlinux and @ann26 
Finally I got time to see where all the emails come from. Since I am not maintaining the projecta for current time, can you remove my email? So that I got less emails everyday.
I will be happy if I can develop it again in the future for sure :)
Thanks :)
> Remove ismail@kartoza.com in the email list.

- django_project/certification/models/certificate.py
fix certificate numbering so that it'll count the certificate for every project:
> fix certificate numbering

- django_project/certification/templates/certifying_organisation/detail.html
when logged in:
when logged out:
> fix info icon

- django_project/certification/views/certificate.py
> fix cache certificate

- django_project/certification/views/certificate.py
> fix view certificate on chrome

- django_project/certification/templates/course_attendee/create.html
> set html body height to 100%

- django_project/certification/views/certificate.py
> remove automated email

- django_project/changes/templates/sponsorship_period/list.html
- django_project/changes/views/sponsorship_period.py
> add sponsor level in list

- django_project/certification/templates/course/create.html
- django_project/changes/templates/sponsorship_period/create.html
- django_project/changes/templates/sponsorship_period/update.html
fix #210 
gif:
also fixes bug in the date input to create a new course:
> add datepicker

- django_project/certification/templates/certificate/regenerate_all_certificate.html
- django_project/certification/templates/certificate/regenerate_certificate.html
- django_project/certification/templates/course/detail.html
- django_project/certification/urls.py
- django_project/certification/views/certificate.py
fix #553 
gif:
rerender a certificate for an attendee:
rerender all certificates in a course:
course details page:
button to rerender all certificates within a course:
confirmation page to rerender all certificates within a course:
button to rerender one certificate for an attendee:
confirmation page to rerender one certificate for an attendee:
> add button to rerender certificates

- django_project/changes/forms.py
- django_project/changes/migrations/0007_auto_20170922_1005.py
- django_project/changes/migrations/0007_auto_20170922_1040.py
- django_project/changes/models/sponsorship_period.py
- django_project/changes/templates/sponsor/detail.html
- django_project/changes/templates/sponsor/list.html
- django_project/changes/templates/sponsorship_period/detail.html
fix #220
form:
sponsor list:
the amount sponsored is displayed when it is available.
sponsorship period details:
when the amount sponsored is available:
when the amount sponsored is not available:
sponsor details: amount sponsored is displayed when it is available.
> add sponsorship amount paid

- deployment/Makefile
Fix #574
Signed-off-by: Tim Sutton <tim@kartoza.com>
> projecta-574 make media sync should sync btsync keys too

- django_project/base/templates/project/new_detail.html
> Removed bold font from sponsers and changelog side blocks.

- .travis.yml
This PR re-enables all tests for travis. See #559
> Make travis run all tests

- django_project/certification/tests/test_credit_systems.py
fix #527 
test is passed in local machine
> add credit system test

- django_project/certification/forms.py
- django_project/certification/migrations/0013_auto_20171014_0827.py
- django_project/certification/migrations/0013_auto_20171014_1045.py
- django_project/certification/models/certifying_organisation.py
- django_project/certification/models/course_convener.py
- django_project/certification/static/css/custom.css
- django_project/certification/templates/certificate/detail.html
- django_project/certification/views/certificate.py
fix #573 and fix #601 
Form:
In the pdf certificate:
When course convener has only title, i.e. Prof.
When course convener has only degree, i.e. MSc.
When course convener has both
In the certificate details page:
When course convener has only title, i.e. Prof.
When course convener has only degree, i.e. MSc.
When course convener has both
This PR also add instruction hours to the certificate when available.
and details page:
> add title and degree course convener

- django_project/changes/feeds/sponsor.py
- django_project/changes/urls.py
> add sponsor feed

- django_project/certification/views/certifying_organisation.py
fix #599
in console:
```
Subject: Projecta - Your organisation is approved
To: tim@kartoza.com
Date: Tue, 24 Oct 2017 07:57:20 -0000
Message-ID: <20171024075720.576.57095@uwsgi>
Dear Tim Sutton,
Congratulations!
Your certifying organisation has been approved. The following is the details of the newly approved organisation:
Name of organisation: New Organisation
Project: XProject
You may now start creating your training center, course type, course convener and course.
For further information please visit: 0.0.0.0:61202/en/x-project/about/
Sincerely,
Anita Hapsari
```
> send email when organisation is approved

- django_project/changes/templates/sponsor/list.html
- django_project/changes/urls.py
- django_project/core/base_templates/project_base.html
> add rss and atom feed icons and fix urls

- django_project/certification/views/certifying_organisation.py
fix #597 
The project owner and certification managers will receive email notification when a new organisation is submitted.
Here's in console:
```
Subject: Projecta - New Pending Organisation Approval
To: tim@kartoza.com
Date: Wed, 25 Oct 2017 04:41:52 -0000
Message-ID: <20171025044152.2359.26306@uwsgi>
Dear Tim Sutton,
You have a new organisation registered to your project: XProject.
You may review and approve the organisation by following this link:
0.0.0.0:61202/en/x-project/pending-certifyingorganisation/list/
Sincerely,
-------------------------------------------------------
This is an auto-generated email from the system. Please do not reply to this email.
```
> send email to certification managers when a new organisation is registered

- django_project/base/templates/project/new_detail.html
- django_project/certification/templates/certifying_organisation/list.html
- django_project/changes/templates/sponsor/list.html
- django_project/changes/templates/sponsor/pending-list.html
- django_project/changes/templates/sponsorship_level/list.html
- django_project/changes/templates/sponsorship_period/list.html
- django_project/changes/templates/version/list.html
- django_project/vota/templates/committee/list.html
fix #580 
Fixed conflict for existing PR https://github.com/kartoza/projecta/pull/642
> fixed conflict for add call to action.

- django_project/base/templates/project/new_detail.html
> Fix certification bar content display on landing page.

- django_project/changes/admin.py
- django_project/changes/forms.py
- django_project/changes/models/sponsor.py
- django_project/changes/models/sponsorship_level.py
- django_project/changes/models/sponsorship_period.py
- django_project/changes/templates/sponsor/list.html
- django_project/changes/templates/sponsor/pending-list.html
- django_project/changes/templates/sponsorship_level/delete.html
- django_project/changes/templates/sponsorship_level/detail.html
- django_project/changes/templates/sponsorship_level/list.html
- django_project/changes/templates/sponsorship_period/delete.html
- django_project/changes/templates/sponsorship_period/list.html
- django_project/changes/views/sponsor.py
- django_project/changes/views/sponsorship_level.py
- django_project/changes/views/sponsorship_period.py
#fix #651 
this PR:
Sponsorship period form
Admin view
Sponsor list view
Sponsorship level view
Sponsorship period view
> restrict sponsors and sponsorship level for a project

- django_project/changes/templates/entry/includes/entry_detail.html
> include 'http' to permalink

- django_project/base/templates/project/new_detail.html
Fix #664 
Hi @timlinux 
How is the looks for the sidepanel content on the screenie above?
Thanks
> Fix sidepanel display

- django_project/certification/tests/model_factories.py
- django_project/certification/tests/test_models.py
> update certification app model CRUD tests.

- deployment/docker/REQUIREMENTS.txt
- django_project/certification/tests/test_models.py
- django_project/core/settings/contrib.py
- django_project/core/settings/project.py
- django_project/lesson/forms/section.py
- django_project/lesson/migrations/0004_auto_20180117_1124.py
- django_project/lesson/migrations/0005_merge.py
- django_project/lesson/translation.py
- django_project/lesson/views/section.py
Ticker: #657 
- Add new section will automatically add translation in the current language.
- Editing will only edit the translation, except English (it will also update the original value).
For @Gustry and @myarjunar, I have registered the fields for all models to be translated. But, you need to use `from modeltranslation.forms import TranslationModelForm` in your ModelForm.
> Internationalisation support for lesson app.

- django_project/lesson/forms/specification.py
- django_project/lesson/forms/worksheet.py
- django_project/lesson/migrations/0006_auto_20180118_2017.py
- django_project/lesson/models/specification.py
- django_project/lesson/templates/specification/create.html
- django_project/lesson/templates/specification/delete.html
- django_project/lesson/templates/specification/includes/specification-list-detail.html
- django_project/lesson/templates/specification/list.html
- django_project/lesson/templates/specification/order.html
- django_project/lesson/templates/specification/update.html
- django_project/lesson/templates/worksheet/includes/worksheet-list-detail.html
- django_project/lesson/tests/model_factories.py
- django_project/lesson/tests/test_specification_model.py
- django_project/lesson/tests/test_specification_view.py
- django_project/lesson/urls.py
- django_project/lesson/views/specification.py
> CRUD views for lesson specification

- django_project/lesson/forms/answer.py
- django_project/lesson/forms/question.py
- django_project/lesson/models/answer.py
- django_project/lesson/models/specification.py
- django_project/lesson/models/worksheet_question.py
- django_project/lesson/templates/answer/create.html
- django_project/lesson/templates/answer/delete.html
- django_project/lesson/templates/answer/update.html
- django_project/lesson/templates/question/create.html
- django_project/lesson/templates/question/delete.html
- django_project/lesson/templates/question/order.html
- django_project/lesson/templates/question/update.html
- django_project/lesson/templates/section/list.html
- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/templates/worksheet/list.html
- django_project/lesson/urls.py
- django_project/lesson/views/answer.py
- django_project/lesson/views/question.py
- django_project/lesson/views/worksheet.py
This PR is adding CRUD for questions and answers.
Ticket #657
> Crud questions

- django_project/lesson/forms/worksheet.py
- django_project/lesson/migrations/0008_auto_20180122_1033.py
- django_project/lesson/models/worksheet.py
Ticket #657 
@myarjunar I will let you tweak the HTML template to render these informations, right?
> add new fields to worksheet: youtube, zip and contacts

- django_project/lesson/admin.py
- django_project/lesson/forms/answer.py
- django_project/lesson/forms/question.py
- django_project/lesson/forms/section.py
- django_project/lesson/forms/specification.py
- django_project/lesson/forms/worksheet.py
- django_project/lesson/migrations/0010_auto_20180123_0959.py
- django_project/lesson/models/worksheet.py
- django_project/lesson/templates/section/includes/section-list-detail.html
- django_project/lesson/templates/worksheet/order.html
- django_project/lesson/urls.py
- django_project/lesson/views/worksheet.py
* Add worksheet order
* improve form title
* fix order in worksheet form
> Add worksheet order, improve form, fix order in worksheet form

- django_project/lesson/admin.py
- django_project/lesson/migrations/0011_auto_20180123_1406.py
- django_project/lesson/models/answer.py
- django_project/lesson/models/section.py
- django_project/lesson/models/specification.py
- django_project/lesson/models/worksheet.py
- django_project/lesson/models/worksheet_question.py
- django_project/lesson/tests/test_section_view.py
- django_project/lesson/utilities.py
- django_project/lesson/views/question.py
- django_project/lesson/views/section.py
- django_project/lesson/views/specification.py
- django_project/lesson/views/worksheet.py
Small refactoring about new order in Lesson app
All our models should have the column named `sequence_number` so we can easily implement the ordering. (for a future app)
> DRY refactoring about new order in Lesson app

- django_project/lesson/migrations/0013_auto_20180127_0626.py
- django_project/lesson/models/worksheet_question.py
Fix the second checkbox listed here: https://github.com/kartoza/projecta/issues/657#issuecomment-360411098
> fix DB constraint on the question table

- django_project/lesson/admin.py
> Tidy up admin page for lessons

- django_project/base/templates/project/new_detail.html
- django_project/core/base_templates/project_base.html
* Need to check the missing block
> fix project permission and missing inheritance in base HTML template

- django_project/certification/templates/certifying_organisation/detail.html
> Add organisation home page link.

- django_project/core/settings/contrib.py
- django_project/lesson/migrations/0017_auto_20180207_1109.py
- django_project/lesson/models/curriculum.py
- django_project/lesson/models/section.py
- django_project/lesson/models/worksheet.py
- django_project/lesson/tests/test_section_view.py
- django_project/lesson/utilities.py
We need to hit the database twice:
* to update the slug based on its current title/name
* include the ID after the first `save`
So now, it will update the slug on every update. Is-it fine to break permalink made before?
> fix uniquness of slug in Lesson app

- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/views/worksheet.py
I will come back later to do something cleaner on all views with a kind of permission mixin
> try to improve permissions in the worksheet view

- deployment/docker/REQUIREMENTS.txt
- django_project/base/templatetags/custom_markup.py
- django_project/lesson/static/css/worksheet_detail_print.css
- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/templates/worksheet/print.html
- django_project/lesson/urls.py
- django_project/lesson/views/worksheet.py
Using weasy print with a custom HTML template:
> add weasy-print

- django_project/certification/templates/certificate/detail.html
Fix #728 
Added a link to certification system on the verify certificate page as per comments in the ticket.
> Added link to the certification platform description.

- django_project/changes/templates/entry/includes/entry_detail.html
> use display block for markdown version description.

- deployment/tag_and_deploy_to_staging.sh
- django_project/core/settings/utils.py
@timlinux Is-it alright to commit and push straight to develop?
> add autocommit on upstream develop in the release script

- django_project/lesson/views/question.py
Sentry: http://sentry.kartoza.com/sentry/django/issues/21/
> fix typo in Lesson app

- django_project/base/templatetags/custom_markup.py
- django_project/core/base_static/css/changelog.css
#723 
WIP
Need to update the CSS
> add CSS for markdown table

- django_project/changes/views/version.py
fix multiple objects returned in version update view
Fix http://sentry.kartoza.com/sentry/projecta/issues/36/
> fix multiple objects returned in version update view

- django_project/changes/views/entry.py
Fix http://sentry.kartoza.com/sentry/projecta/issues/41/
* remove unnecessary code (already done by the django framework)
* don't use `self` everytime to store variable, it makes it harder to know which variable are global in `self` or local to a method
* fix fetching Version object only with its slug, use the project too.
> remove unnecessary code, version slug is not unique so fetch it with the project too

- django_project/changes/feeds/entry.py
Fix http://sentry.kartoza.com/sentry/projecta/issues/42/
> fix multiple objects returned in version feed

- django_project/certification/views/certifying_organisation.py
Fix http://sentry.kartoza.com/sentry/projecta/issues/39/
Fix http://sentry.kartoza.com/sentry/projecta/issues/29/
> fix unicode characters when we send an email in the certification app

- README-dev.md
- deployment/Makefile
- django_project/core/settings/dev_docker.py
- django_project/core/settings/prod_docker.py
Some small improvements (trying to jump into the projecta wagon again)
> Small Improvement

- django_project/core/base_templates/includes/right-nav.html
> show username in menue bar

- django_project/core/base_templates/includes/right-nav.html
Add caret to language dropdown.
> add caret to language dropdown

- django_project/certification/templates/attendee/upload_attendee_csv.html
> fix csv upload instruction

- django_project/changes/views/sponsor.py
> Handle queryset exception.

- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/views/certifying_organisation.py
- django_project/changes/views/version.py
- django_project/lesson/views/worksheet.py
fix #807 
Logged in as an owner you are now able to CRUD training centre, course type as well as course converners too.
> fix permission with clean checks

- deployment/Makefile
- deployment/README-docker.md
- deployment/deploy_to_production.sh
- deployment/tag_and_deploy_to_staging.sh
* remove run from makefile - it is redundant
* readme updates
* fix issue with deploy scripts not backing up remote db properly
> Helper scripts

- django_project/lesson/forms/question.py
- django_project/lesson/migrations/0024_auto_20180312_1726.py
- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/templates/worksheet/print.html
- django_project/lesson/translation.py
Fix #835 
Fix #838,
Fix #840, 
Fix #842,
Fix #843,
Fix #831 
I didn't change the print template, it looks good:
[133.pdf](https://github.com/kartoza/projecta/files/1803574/133.pdf)
Update:
Question's image:
> Fix #838, #840, #842, #843, #831, #835

- django_project/lesson/migrations/0025_auto_20180313_0955.py
- django_project/lesson/models/specification.py
- django_project/lesson/templates/worksheet/detail.html
fix #828 
Add markdown support to  requirements table content.
> Add markdown support.

- django_project/lesson/migrations/0026_auto_20180314_0438.py
- django_project/lesson/models/answer.py
- django_project/lesson/models/section.py
- django_project/lesson/models/worksheet.py
Small changes, I will merge if the Travis allowed.
> Fix #850, remove text field max_length in lesson app.

- django_project/lesson/templates/section/includes/section-list-detail.html
- django_project/lesson/templates/section/list.html
- django_project/lesson/views/section.py
fix #819 
Enable pagination in template.
> fix section list limit

- django_project/lesson/templates/worksheet/print.html
@sonlinux Follow up after https://github.com/kartoza/projecta/pull/844
> fix missing markdown in PDF rendering

- django_project/base/models/project.py
- django_project/base/views/error_views.py
- django_project/base/views/github_project.py
- django_project/base/views/project.py
- django_project/changes/models/category.py
- django_project/changes/models/entry.py
- django_project/changes/models/sponsor.py
- django_project/changes/models/sponsorship_level.py
- django_project/changes/models/sponsorship_period.py
- django_project/changes/models/version.py
- django_project/changes/views/category.py
- django_project/changes/views/entry.py
- django_project/changes/views/sponsor.py
- django_project/changes/views/version.py
- django_project/core/settings/prod_docker.py
- django_project/lesson/forms/question.py
- django_project/lesson/forms/section.py
- django_project/lesson/forms/specification.py
- django_project/lesson/tests/model_factories.py
- django_project/lesson/views/question.py
- django_project/lesson/views/section.py
- django_project/lesson/views/specification.py
- django_project/vota/models/ballot.py
- django_project/vota/models/vote.py
@sonlinux `"""([a-zA-Z ]*)"""` to `"""$1."""` in PyCharm to do it automatically
> add full stop at the end of one line docstring

- django_project/changes/views/entry.py
- django_project/lesson/templates/section/includes/row-worksheet.html
- django_project/lesson/templates/section/includes/section-list-detail.html
- django_project/lesson/templates/section/list.html
- django_project/lesson/views/question.py
- django_project/lesson/views/section.py
- django_project/lesson/views/specification.py
- django_project/lesson/views/worksheet.py
If the user is only manager, staff permission is not enough to display that page
> If the user is only manager, staff permission is not enough to display that page

- django_project/lesson/templates/worksheet/print.html
- django_project/locale/en/LC_MESSAGES/django.po
- django_project/locale/id/LC_MESSAGES/django.po
> Add http:// to the data url in pdf lesson.

- django_project/lesson/templates/worksheet/detail.html
> fix buttongroup display

- .travis.yml
> Replace coveralls with codecov.

- django_project/lesson/migrations/0027_auto_20180410_1007.py
- django_project/lesson/models/worksheet.py
fix #836 
Remove mandatory fields on worksheet detail.
> Remove mandatory fields

- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/templates/worksheet/print.html
- django_project/lesson/views/worksheet.py
> Hide unavailable sections

- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/templates/worksheet/print.html
> Fix worksheet exercise section 

- django_project/certification/templates/course/update.html
> add preview existing template certificate

- django_project/lesson/templates/worksheet/detail.html
> Fix #897 can not add more than one question.

- django_project/core/base_templates/project_base.html
> change text colour

- django_project/changes/templates/version/detail.html
fix #905 via #906 
On version create, allow authenticated users to see create action button.
> allow authenticated users to see create action

- django_project/changes/feeds/sponsor.py
- django_project/changes/urls.py
@timlinux @ann26 is this ok? To retrieve the past sponsors?
> Add a feed to retrieve the rss feed for past/former sponsors

- django_project/certification/views/certificate.py
fix http://sentry.kartoza.com/sentry/projecta/issues/136/
> fix encoding for emailing participants

- django_project/changes/templates/version/list.html
- django_project/changes/views/version.py
And make the code a little bit better
> Fix logic in version list template.

- django_project/changes/feeds/version.py
- django_project/changes/templates/category/list.html
- django_project/changes/tests/test_models.py
- django_project/changes/views/category.py
Follow up for this comment: https://github.com/kartoza/prj.app/pull/951#discussion_r193538544
and more clean up
> Move cleaning up about pending state.

- django_project/certification/templates/certificate/detail.html
Minor change on certificate info web page.
> Fix typo in certificate details

- django_project/certification/views/certifying_organisation.py
hi @timlinux ,
Alison might have accidentally changed the template.
> fix certification about page

- django_project/lesson/templates/section/includes/section-list-detail.html
- django_project/lesson/tests/test_worksheet_views.py
- django_project/lesson/views/worksheet.py
hi @timlinux with this PR I made the answers publicly available.
Here's gif when user is not logged in:
> make answer publicly available

- README-dev.md
- README.md
- deployment/docker/REQUIREMENTS.txt
- django_project/changes/tests/test_rss_view.py
It's needed to avoid installing the latest WeasyPrint that only supports Python 3
> Set version for WeasyPrint.

- django_project/core/settings/base.py
- django_project/lesson/static/css/section-list.css
- django_project/lesson/static/js/download_multiple_files.js
- django_project/lesson/templates/section/includes/row-worksheet.html
- django_project/lesson/templates/section/includes/section-list-detail.html
- django_project/lesson/templates/section/list.html
- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/urls.py
- django_project/lesson/views/worksheet.py
This PR:
Sections numbering
Match title pdf
match title zip
This button will download the pdf module and sample test into one zip file
When translation is not available, item is hidden
english
indonesian
> tweak lesson app

- django_project/lesson/static/js/download_multiple_files.js
- django_project/lesson/templates/section/includes/row-worksheet.html
- django_project/lesson/views/worksheet.py
Download individual worksheet:
Download multiple worksheet:
PS: I haven't succeed to extract the zip file and put it in downloaded zip
> add numbering upon download

- deployment/docker/REQUIREMENTS.txt
- django_project/changes/feeds/json_rss_feed.py
- django_project/changes/feeds/sponsor.py
- django_project/changes/tests/model_factories.py
- django_project/changes/tests/test_json_rss_feed.py
- django_project/changes/tests/test_rss_view.py
> Fix createjson PR

- django_project/changes/feeds/sponsor.py
- django_project/changes/tests/test_rss_view.py
Adding years limit to the RSS Feed of past sponsors, requested by @rduivenvoorde 
Sample request:
Without any limit (show all past sponsors):
```
http://0.0.0.0:61202/en/project-name/past-sponsors/rss/
```
Result:
```
<?xml version="1.0" encoding="utf-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" version="2.0">
<channel>
<title>RSS Sponsors of Project Name Project</title>
<link>http://example.com/en/project-name/</link>
<description>These are the past sponsors of Project Name project.</description>
<atom:link href="http://example.com/en/project-name/past-sponsors/rss/" rel="self"></atom:link>
<language>en-us</language>
<lastBuildDate>Thu, 07 Mar 2019 20:54:58 -0000</lastBuildDate>
<item>
<title>Old Sponsor</title>
<link>http://example.com/en/project-name/sponsorshipperiod/zradvr/</lin …
```
> Add Years Limit to Past Sponsorship RSS Feed 

- django_project/lesson/templates/section/includes/row-worksheet.html
- django_project/lesson/templates/worksheet/detail.html
- django_project/lesson/templates/worksheet/print.html
- django_project/lesson/views/worksheet.py
Add numbering in rendered page:
Site:
PDF:
> add numbering in rendered page

- django_project/vota/templates/ballot/create.html
- django_project/vota/templates/ballot/update.html
fix #1018 
Fix date which shows `NaN` on safari. 
This inject date using javascript.
> fix date for safari

- django_project/certification/forms.py
add space between username on the list so that we can search the username too in the list.
> improve search convener

- django_project/vota/models/ballot.py
- django_project/vota/templates/ballot/detail.html
- django_project/vota/templates/ballot/includes/ballot-vote-details.html
- django_project/vota/views/ballot.py
fix #1024 
This PR:
when ballot open:
when ballot closed:
> hide choices when ballot closed

- django_project/vota/models/vote.py
- django_project/vota/templates/ballot/includes/ballot-vote-details.html
- django_project/vota/views/ballot.py
> add modal to show voters

- django_project/changes/feeds/json_feed.py
- django_project/changes/feeds/sponsor.py
continuing #1046 
JSON feed
```
{
"rss": {"version": "2.0", "channel": 
{
"lastBuildDate": "Fri, 18 Oct 2019 08:45:38 -0000", 
"link": "http://changelog.kartoza.com/en/qgis/", 
"description": "These are the members of QGIS project.", 
"item": [{
"description": "", 
"end_date": "05 March 2020", 
"title": "Spatial Networks, Inc.",
"member_level": "Medium", 
"member_country": "United States of America", 
"image_url": "http://changelog.kartoza.com/media/images/projects/ae367e8695ac064fa15a4e0ee37714f796f26255.png", 
"link": "http://changelog.kartoza.com/en/qgis/sponsorshipperiod/oenuqs/", 
"member_url": "https://spatialnetworks.com/", 
"guid": "http://changelog.kartoza.com/en/qgis/sponsorshipperiod/oenuqs/", 
"start_date": "05 March 2019"
},
```
> update feed to use member

- django_project/changes/templates/entry/detail.html
- django_project/changes/templates/version/detail.html
- django_project/core/settings/contrib.py
- django_project/vota/templates/ballot/detail.html
Removing disqus because of unwanted ads.
> remove disqus from pages

- django_project/certification/views/certificate.py
> improve certificate layout

- django_project/certification/admin.py
> add project name for certifying organisation admin

- django_project/lesson/templates/worksheet/detail.html
fix #1022
Before fix:
After fix:
> fix numbering for questions for firefox

- django_project/lesson/templates/worksheet/detail.html
> always show button

- django_project/certification/views/certificate.py
> fix unicode text

- django_project/changes/tests/test_sustaining_member_views.py
- django_project/changes/views/sustaining_member.py
> Add metadata for subscription

- django_project/changes/views/version.py
- django_project/lesson/views/worksheet.py
Another fixes due to python update
> Fix zipfile

- django_project/certification/models/course_convener.py
- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/course/create.html
- django_project/certification/templates/course/update.html
- django_project/certification/templates/course_type/create.html
- django_project/certification/templates/course_type/update.html
- django_project/certification/views/course.py
- django_project/certification/views/course_type.py
Fix #1115, Fix #1116, Fix #1117
> Bugs fixing

- django_project/certification/forms.py
- django_project/certification/templates/certifying_organisation/detail.html
- django_project/certification/templates/training_center/create.html
- django_project/certification/templates/training_center/update.html
- django_project/certification/views/training_center.py
Fix https://github.com/kartoza/prj.app/issues/1119
> Fix add/update training centre

- django_project/certification/views/certificate.py
> Fix certificate

- django_project/certification/views/attendee.py
> fix csv uploader

- django_project/certification/templates/course/detail.html
- django_project/certification/views/certificate.py
> fix character

- django_project/certification/views/certificate.py
> fix preview certificate

- django_project/changes/admin.py
- django_project/changes/templates/pinax/notifications/email_body.txt
- django_project/changes/views/sustaining_member.py
> fix current domain

- django_project/certification/views/certificate.py
> fix download certificates as a zip

- django_project/certification/static/docs/example.csv
- django_project/certification/templates/attendee/upload_attendee_csv.html
- django_project/certification/views/attendee.py
> fix course attendee bulk upload

- django_project/certification/templates/course/update.html
> fix template certificate on update

- django_project/core/settings/project.py
> fix login url

- MAINTAINERS
- README.md
- django_project/certification/templates/course/detail.html
- django_project/core/base_templates/includes/base-auth-nav-left.html
> add menu and fix permissions

- django_project/base/forms.py
- django_project/base/templates/account/profile.html
- django_project/base/templates/account/update.html
- django_project/base/urls.py
- django_project/base/views/__init__.py
- django_project/base/views/user.py
- django_project/core/base_templates/includes/right-nav.html
fix #1148 
@timlinux what do you think?
Note: only the user itself can open the edit page for his profile.
> add user profile page

- django_project/certification/feeds/geojson_feed.py
- django_project/certification/feeds/training_center.py
- django_project/certification/templates/certifying_organisation/list.html
- django_project/certification/urls.py
> add feed for training center within a project

- django_project/changes/views/version.py
> add exception when file does not exist

- django_project/changes/views/version.py
> fix image location
