django_project/changes/views/version.py
Hi @timlinux In this PR, I've changed pypandoc endocding from `ascii` to `utf8`. Refer to #131.
How do you think? 
Thanks.
=> change pypandoc encoding from ascii to utf8 | fixes #131

django_project/base/views/error_views.py
Hi @timlinux 
After trial and error, its make me confused because everything is running well when debug= `True` but when we change debug=`False` (on production) it will 404 page. 
The problem is `handler404`
I just add 
```
response.status_code = 404
return response
```
To make sure that the response is only when the status_code = 404.
and now it works well. You can open this link [http://128.199.97.119:61200/](http://128.199.97.119:61200/)
Now, it will automatically redirect on the production. 
And the translation it should works too. 
Thanks
=> fixes #147 | 404 landing page

django_project/base/models/project.py, django_project/base/views/project.py
Hi @timlinux 
For the pending items, as I told you before the problem is `def get_query_set` it should `def get_queryset`
I've checked that for the `category`, `version`, `sponsor` I've fixed in previous PR. 
Now, This PR is for the project, I've fixed it. 
and also I changed the redirect url, previous after user approve the project it will be redirected to the pending-items, now it will redirect to home. 
Thanks
=> Fixing pending items | Fixes #138

django_project/changes/tests/model_factories.py, django_project/changes/tests/test_models.py, django_project/changes/tests/test_views.py, django_project/changes/views/sponsor.py, django_project/changes/views/sponsorship_level.py, django_project/changes/views/sponsorship_period.py
Hi @timlinux 
In this PR, I've added some view tests for the sponsors stuff and all tests have been passed. 
btw, did you try my previous PR within your machine? 
I am bit confused for the error. 
I've tried many times with new docker containers and in my ubuntu server too, and it works well. 
The code is like this:
```
def current_sponsor(self):
today = timezone.now()
end = self.end_date
if end < today:
return False
```
end_date model 
```
end_date = models.DateField(
_("End date"),
help_text='End date of sponsorship period',
default=timezone.now)
```
As my understanding, it should works. If I use `datetime` it will produce error ` can't subtract offset-naive and offset-aware datetimes`. So we have to replace `tzinfo` like in [this …
=> Sponsors view test

deployment/docker/REQUIREMENTS-dev.txt, django_project/changes/templates/sponsor/list.html, django_project/changes/templates/sponsorship_level/detail.html, django_project/changes/templates/sponsorship_level/list.html, django_project/changes/templates/sponsorship_period/list.html, django_project/core/base_templates/includes/base-auth-nav-left.html, django_project/core/base_templates/includes/right-nav.html, django_project/vota/templates/committee/list.html
=> Hide pending and management menu from non staff 

django_project/changes/templates/version/list.html, django_project/changes/views/version.py
Hi @timlinux  this PR based on Issue #298 
Now we are able to add version when the version is empty.
=> Added "add new version" when version is empty

django_project/changes/templates/version/detail.html, django_project/changes/urls.py, django_project/changes/views/version.py
This PR is for #290 
Hi @timlinux 
How about this one? 
The result is like this file ->
[QGIS-Sponsor-2.14.0.zip](https://github.com/kartoza/projecta/files/330925/QGIS-Sponsor-2.14.0.zip)
The result of files after extracted. 
If I open in web browser
=> Added sponsor list download as html

django_project/changes/templates/sponsorship_period/delete.html, django_project/changes/templates/sponsorship_period/detail.html, django_project/changes/views/sponsorship_level.py, django_project/changes/views/sponsorship_period.py
Hi Tim, 
This PR for #304 
There is also some fixing after I checked. 
These are the screenshoot:
Update sponsorship period:
Adding more information on the delete confirmation page of sponsorship period: 
Update sponsorship level:
I have tried to update and delete from both of features and all work. 
Thanks
=> Fixed Edit for sponsorship period and sponsorship level

django_project/changes/templates/sponsor/detail.html
Hi @timlinux this PR for #305 
This is the view after fixed
=> fixes #305 visual style of sponsor detail

django_project/base/templates/button_span.html, django_project/base/templates/project/detail.html, django_project/base/templates/project/includes/project-panel.html, django_project/base/templates/project/list.html, django_project/base/templatetags/custom_markup.py, django_project/changes/templates/category/list.html, django_project/changes/templates/entry/list.html, django_project/changes/templates/entry/pending-list.html, django_project/changes/templates/sponsor/list.html, django_project/changes/templates/sponsor/pending-list.html, django_project/changes/templates/sponsorship_level/list.html, django_project/changes/templates/sponsorship_period/list.html, django_project/changes/templates/version/detail.html, django_project/changes/templates/version/list.html, django_project/core/base_templates/includes/base-auth-nav-left.html, django_project/vota/templates/ballot/list.html, django_project/vota/templates/committee/includes/committee-panel.html, django_project/vota/templates/committee/list.html
=> Cleanup navbar and buttons

django_project/changes/models/sponsorship_period.py, django_project/changes/templates/sponsorship_period/list.html, django_project/changes/views/sponsorship_period.py
Hi @timlinux this PR for #303 
This is the screenshot of new sponsorship periods. 
[Organisation][start] - [end][view icon]
=> Fixed issue 303 Sponsorship periods view

django_project/changes/templates/version/detail-content.html, django_project/changes/templates/version/includes/version-list-detail.html
Hi @timlinux this PR for #278 
The results:
=> Added release date information on the version and version list page

django_project/changes/templates/sponsor/pending-list.html, django_project/changes/templates/sponsorship_level/list.html, django_project/changes/templates/sponsorship_period/list.html
Hi @timlinux 
There are two missing `</a>` so it makes page broken. 
And also, the head of table now is hidden when sponsorship period is empty. 
Previously:
Thanks.
=> Pending items broken

django_project/changes/templates/sponsor/list.html, django_project/changes/views/sponsor.py
Hi @timlinux this PR for #281 issue
It seems this already fulfilled the requirements based on the comments
Sponsor level will not showed if there is no sponsor for that level, and I have change the pagination page to 1000.
Thanks.
=> Fixing sponsor list view

django_project/changes/views/version.py
Hi @rduivenvoorde 
Thanks for your comment https://github.com/kartoza/projecta/issues/340. It seems now is without break line.
=> Export rst without break lines

django_project/changes/migrations/0006_auto_20160718_0804.py, django_project/vota/migrations/0002_auto_20160718_0808.py, django_project/vota/models/ballot.py
fixing vota model bug that will create new migrations every "make update-migrations" executed
_note_:
django_project/changes/migrations/0006_auto_20160718_0804.py is added too because it seems that when SponsorshipPeriod meta model was changed but not migrated yet
=> fixing vota model

django_project/base/templates/project/includes/project-panel.html, django_project/core/base_templates/includes/base-auth-nav-left.html
@timlinux @cchristelis @dimasciput 
i found bug that pending project is shown in "all project" navbar
_on landing page, i made test1_
_when click, it show "page not found"_
_i changed it by giving "pending" indicator_
_and redirect to pending project list_
=> bug fixing : pending project is shown in all project

django_project/base/templatetags/custom_markup.py, django_project/changes/templates/entry/pending-list.html
To address this issue https://github.com/kartoza/projecta/issues/239 I added back button on entries page. What do you think?
=> Add back button on entries page

django_project/changes/forms.py, django_project/changes/templates/category/list.html, django_project/changes/views/category.py
Issue #347 
- Fix duplicate category name
- Fix category list in entry form is not filtered to the project
- Remove pagination in category list
- Creating a new category gives 500 when approving ( **_Can't reproduce this error_** )
- Creating a new category gives 500 when deleting a pending category ( **_Can't reproduce this error_** )
=> Fix category management

django_project/base/templates/project/includes/project-panel.html, django_project/base/views/project.py, django_project/changes/models/version.py, django_project/changes/views/version.py
here is the changes for this PR:
- version cannot be created for pending project
- pending version just be shown for logged in user (for the future, just for project administrator and collaborator, related with : https://github.com/kartoza/projecta/issues/349)
- pending version in project panel will redirect too pending version list view
- when changing pending project, it will be redirect to pending project list instead detail that not found
- make cannot access pending version listview for pending project 
_authenticated_
__not authenticated_
this fix #357
=> fixing bug on pending version acceptance

django_project/changes/templates/sponsor/detail.html, django_project/changes/views/sponsor.py, django_project/changes/views/version.py, django_project/core/base_static/css/changelog.css
- Hide personal data for unauthenticated user ( Fix #362 )
- Update sponsor detail layout
**Sponsor view for authenticated user**
**Sponsor view for unauthenticated user**
=> Update sponsor detail view

django_project/core/base_static/css/changelog.css
Solving issue #386 
I edited changelog.css file.
The code should limit the image width so it will become like this:
=> limit image width

django_project/certification/forms.py, django_project/certification/models/course_type.py, django_project/certification/templates/certifying_organisation/detail.html, django_project/certification/templates/course_type/create.html, django_project/certification/templates/course_type/delete.html, django_project/certification/templates/course_type/detail.html, django_project/certification/templates/course_type/update.html, django_project/certification/urls.py, django_project/certification/views/__init__.py, django_project/certification/views/course_type.py
fix #410 
when user click on `create one` or `*` button
it will go to create course type page:
when it is done, it will come back to organisation details page:
when user click on :pencil2: button next to course type name, it will direct them to update page
update page layout is the same as create page layout.
when update is done, user is directed to organisation details page.
when user click on :heavy_minus_sign: button next to course type name, it will direct them to delete page
delete page
click on :heavy_minus_sign: will delete the course type while click on :arrow_left: button will cancel and direct the user to organisation detail page
when user click on the name of course type link, it will direct them to detail page
from detail page, they can click on buttons to edit or delete or to …
=> add create page for course type

django_project/certification/views/certificate.py
fix #472 
the certificate now:
the url (depends on domain name):
=> fix url at certificate

django_project/certification/forms.py
In the organisation add/edit page:
for organisation owners:
=> use real name for organisation owners

deployment/sites-enabled/default.conf, django_project/core/settings/dev_docker.py
fix #394 
This PR configures nginx, so that it only accepts connections for specific hosts (server_name).
Also add allowed host for dev
=> add server name in nginx conf

django_project/certification/forms.py, django_project/certification/templates/course/create.html, django_project/certification/templates/course/update.html
This PR add validation for input course start date and end date
=> add course date validation

django_project/certification/forms.py
When a user create an organisation, he will be automatically chosen as an organisation owner.
=> add user automatically as default organisation owner

django_project/certification/views/certificate.py
fix #473 
I tried in development, when issuing certificate for:
attendee (name: Jane Austen, email: anita.nhapsari@gmail.com)
sender using convener's email and convener's name at the end of the email.
the output in console is this
```
Subject: Certificate from QGIS Introduction Course
To: anita.nhapsari@gmail.com
Date: Wed, 26 Jul 2017 09:44:51 -0000
Message-ID: <20170726094451.366.84755@uwsgi>
Dear Jane Austen,
Congratulations!
Your certificate from the following course has been issued.
Course type: QGIS Introduction
Course date: 01 July 2017 to 31 July 2017
Training center: training center A
Certifying organisation: OrganisationX
You may check the full details of the certificate by visiting:
http://changelog.kartoza.com/en/x-project/certificate/XProject-3/ …
```
=> send email to attendee when certificate is issued

django_project/certification/templates/course/detail.html, django_project/certification/urls.py, django_project/certification/views/certificate.py
Download all issued certificates in one course as one zip file
In course details page:
When the download button is clicked, user can save/view the zip file:
The zip file contains folder with course name and all issued certificates is inside that folder:
=> download certificates as a zip

django_project/certification/forms.py, django_project/certification/migrations/0010_auto_20170817_1718.py, django_project/certification/models/certifying_organisation.py
fix #496
this PR includes:
in admin:
=> add project name in listing admin page

django_project/certification/templates/certifying_organisation/detail.html
fix #500
for non logged in users:
=> fix edit buttons

django_project/certification/models/certifying_organisation.py, django_project/certification/templates/certifying_organisation/detail.html, django_project/certification/templates/course/detail.html
fix #483 
This PR:
organisation slug is using project slug, thus: project slug-organisation name e.g. qgis-kartoza
=> fix organisation slug and improve course name display

django_project/certification/views/certificate.py
fix #510
in console, the email is as follows:
```
Subject: Certificate from Coding for Dummies Course
To: janeausten@gmail.com
Date: Mon, 21 Aug 2017 09:28:12 -0000
Message-ID: <20170821092812.5206.24232@uwsgi>
Dear Jane Austen,
Congratulations!
Your certificate from the following course has been issued.
Course type: Coding for Dummies
Course date: 11 July 2017 to 19 December 2017
Training center: training center B
Certifying organisation: OrganisationX
You may print the certificate by visiting:
http://0.0.0.0:61202/en/x-project/certifyingorganisation/xproject-organisationx/course/xproject_coding-for-dummies_2017-07-11-2017-12-19/print/37/
Sincerely,
Anita Hapsari
```
The …
=> fix certificate url

django_project/base/templates/project/list.html, django_project/base/views/project.py, django_project/certification/templates/certifying_organisation/pending-list.html, django_project/certification/views/certifying_organisation.py, django_project/core/settings/base.py
fix #504 
in the dashboard project list:
when user registered an organisation:
when a new organisation is registered, an email is sent to project owner:
```
Subject: Projecta - New Pending Organisation Approval
To: anita@kartoza.com
Date: Wed, 06 Sep 2017 10:07:55 -0000
Message-ID: <20170906100755.2961.91902@uwsgi>
Dear Anita Hapsari,
You have a new organisation registered to your project: XProject.
You may review and approve the organisation by following this link:
0.0.0.0:61202/en/x-project/pending-certifyingorganisation/list/
Sincerely,
----------------------------------------------------------
This is an auto-generated email from the system. Please do not reply to this …
```
=> add notification for pending organisation

django_project/certification/views/certificate.py
fix #506 
Certificates are now generated once, stored in /media/pdf/<certificateid>.pdf and served from there.
=> Certificates should be cached

django_project/certification/templates/certificate/send_email_confirm.html, django_project/certification/templates/course/detail.html, django_project/certification/urls.py, django_project/certification/views/certificate.py
fix #545 
icon in course details page:
confirm page:
gif:
email content:
```
Dear Jane Austen,
Congratulations!
Your certificate from the following course has been issued.
Course type: Coding for Dummies
Course date: 11 July 2017 to 19 December 2017
Training center: training center B
Certifying organisation: OrganisationX
You may print the certificate by visiting:
http://0.0.0.0:61202/en/x-project/certifyingorganisation/xproject-organisationx/course/xproject_coding-for-dummies_2017-07-11-2017-12-19/print/37/
Sincerely,
Anita Hapsari
```
=> add send email to all attendees with paid certificate

django_project/certification/forms.py, django_project/certification/migrations/0012_auto_20170922_0649.py, django_project/certification/models/course.py, django_project/certification/models/course_type.py
=> add function to increment slug

django_project/certification/templates/certifying_organisation/pending-list.html, django_project/certification/views/certifying_organisation.py, django_project/changes/templates/category/list.html, django_project/changes/views/entry.py
fix #524 
This PR
------------------------------------------------------------------------------------------------------------------------
In this example, there are 2 pending organisations.
when user is a staff or project owner:
when user is the organisation's owner of `test anitan` organisation:
when user is not a staff nor creator of any pending organisation:
----------------------------
This PR also removes the edit and view button in the category pending approval:
-----------------------
From what I have checked, the other pending views are already strictly only for staff, other user cannot see them. Here's what happen when a non staff user wants to see category / version / entry pending view:
=> fix pending page

django_project/base/static/css/project-details.css, django_project/base/templates/project/includes/project-panel.html, django_project/base/templates/project/new_detail.html, django_project/base/views/project.py
fix #564 
This PR:
home page:
project landing page:
=> update landing page style

django_project/changes/templates/sponsorship_period/list.html, django_project/changes/views/sponsorship_period.py
=> show amount sponsored and retrofill data

django_project/base/templates/project/includes/project-panel.html, django_project/base/templates/project/list.html, django_project/core/base_templates/includes/base-auth-nav-left.html
fix #565
home page
navbar
when the logo is rectangle
when the logo is square
=> fix thumbnail display

django_project/base/tests/test_views.py, django_project/changes/tests/test_views.py, django_project/vota/tests/test_views.py
See #581 
This commit fixes issues with tests that require a logged in user.
I fixed the issues by adding lines like this in each place where we use the user factory:
self.user.set_password('password')
self.user.save()
There are still some tests failing due to missing css and js libs - will try to address those in a separate PR.
Fix #581
Signed-off-by: Tim Sutton <tim@kartoza.com>
Before fix:
After fix:
=> Fix failing tests due to client login not working

django_project/base/templates/project/new_detail.html
=> changed side block title from 'Releases (Changelogs)' to 'Release Changelogs'

django_project/changes/templates/sponsor/list.html, django_project/changes/templates/sponsor/sponsor_cloud.html, django_project/changes/urls.py, django_project/changes/views/sponsor.py
fix #230 
The button in the sponsors page:
Page showing the generated image:
4 icon sizes are available depending on the rank of the sponsorship level in the current sponsors: 100px, 75px, 50px and 25px.
When current sponsor is not available:
=> add sponsor cloud

django_project/base/forms.py, django_project/base/migrations/0008_project_sponsorship_programme.py, django_project/base/models/project.py, django_project/base/templates/project/programme.html, django_project/base/urls.py, django_project/base/views/project.py, django_project/changes/templates/sponsor/list.html
fix #219 
Button to view sponsorship programme in a project:
when user is logged in
when user is not logged in
When empty
For staff user and project owner:
for other users:
When is not empty
for staff user and project owner
for other users:
=> add sponsorship programme

django_project/base/templates/project/list.html, django_project/core/base_templates/includes/base-auth-nav-left.html
before fix (in safari and chrome):
after fix (tested in chrome):
=> fix display icon

django_project/certification/views/certifying_organisation.py
fix #598 
The applicant will receive an email notification when he submitted his organisation, with contact person including project's owner and certification managers.
On console:
```
Subject: Projecta - Your Organisation is Successfully Submitted
From: tim@kartoza.com
To: anita@kartoza.com
Date: Wed, 25 Oct 2017 05:29:57 -0000
Message-ID: <20171025052957.2627.32361@uwsgi>
Dear Anita Hapsari,
Your organisation is successfully submitted.
It is now waiting for an approval from the project's owner and certification managers.
If you have not heard from us in few weeks you may contact us:
Tim Sutton: tim@kartoza.com
Ismail Sunni: ismail@kartoza.com
Dimas Ciputra: dimas@kartoza.com
Sincerely,
```
=> send email to applicant on submit

django_project/base/migrations/0010_auto_20171027_0525.py, django_project/base/models/project.py
fix #624 
I copied the content from here as example: http://www.qgis.org/en/site/getinvolved/governance/sponsorship/sponsorship.html
=> make sponsor programme field longer

django_project/certification/templates/course/detail.html
Fix #629
Do not show organisational related private details to non organisational owners or staff or admin users.
=> Hide organisational private related details from non-logged in user.

django_project/certification/views/certifying_organisation.py
In console:
```
Subject: Projecta - New Pending Organisation Approval
To: anita@kartoza.com
Date: Mon, 04 Dec 2017 08:24:22 -0000
Message-ID: <20171204082422.254.73420@uwsgi>
Dear Anita Hapsari,
You have a new organisation registered to your project: XProject.
Organisation name: New Organisation Submitted
Country: Indonesia
You may review and approve the organisation by following this link:
0.0.0.0:61202/en/x-project/pending-certifyingorganisation/list/
Sincerely,
-------------------------------------------------------
This is an auto-generated email from the system. Please do not reply to this email.
```
=> add organisation name and country to email notification

django_project/base/templates/project/new_detail.html
Fix #644 
Make content block items clickable.
=> make block contents clickable.

django_project/base/admin.py, django_project/base/forms.py, django_project/base/migrations/0012_project_sponsorship_manager.py, django_project/base/models/project.py, django_project/certification/views/certifying_organisation.py, django_project/changes/templates/sponsor/detail.html, django_project/changes/templates/sponsor/pending-list.html, django_project/changes/templates/sponsorship_period/delete.html, django_project/changes/templates/sponsorship_period/detail.html, django_project/changes/templates/sponsorship_period/list.html, django_project/changes/views/sponsor.py, django_project/changes/views/sponsorship_level.py, django_project/changes/views/sponsorship_period.py
fix #646 
Added edit and delete button on sponsor details page. Staff, project owner, project changelog manager and the author of the sponsor can update/delete it.
For other logged in users
For non-logged in users
=> fix permissions

.travis.yml
Waiting for this patch: https://code.djangoproject.com/ticket/28973
Meanwhile, this is dividing our logs per 2! (3000 lines before, 1300 with this PR), much much better to scroll down and check why travis is failing.
=> make travis muted for collectstatic

django_project/lesson/views/question.py, django_project/lesson/views/section.py, django_project/lesson/views/specification.py
Ah, it seems the DB got me! Since my commit to add some constraints on the order number, the ordering is not working anymore.
If we could update the DB in a transaction (without integrity constraints), everything would be good because the JSON from the ajax request is correct according the DB. But because the `save` is done separately on each record in the DB, it's failing.  I checked the Django doc but I'm not sure we can disable integrity constraints by doing a bulk update command.
As we won't have a big lesson with thoussand of worksheets, I think it's fine to do this small dummy temporary shift in the DB. What do you think @timlinux ? Or should I disable my work on `unique_together`.
=> add a dummy shift in DB to avoid Integrity Error

django_project/base/forms.py, django_project/base/migrations/0015_project_lesson_manager.py, django_project/base/models/project.py, django_project/changes/views/category.py, django_project/lesson/templates/section/includes/row-worksheet.html, django_project/lesson/templates/section/includes/section-list-detail.html, django_project/lesson/templates/section/list.html, django_project/lesson/templates/worksheet/detail.html, django_project/lesson/views/question.py, django_project/lesson/views/section.py, django_project/lesson/views/specification.py, django_project/lesson/views/worksheet.py
I think a few things to check on Projecta how permissions are done.
I tried a non-admin account on changelog.qgis.org, I can see icons to remove. But then I can't get the webpage. It's confusing to display it if we have a 302 error after.
Can you tell me also why the mixin `LoginRequiredMixin` is enough in this view? To remove a project, you shouldn't need only a login, you need a staff login for instance `StaffuserRequiredMixin` or to be the project owner.
https://github.com/kartoza/projecta/blob/develop/django_project/base/views/project.py#L166
=> add permissions on lesson app, review mixin

django_project/certification/templates/certifying_organisation/detail.html, django_project/certification/templates/certifying_organisation/list.html, django_project/changes/templates/category/list.html, django_project/changes/templates/version/list.html, django_project/changes/views/category.py, django_project/changes/views/sponsor.py, django_project/changes/views/version.py
fix #689 
This PR:
changelog managers can see create button and should be able to create, update and delete versions
add clickable about link
=> fix permissions and add about link

django_project/base/migrations/0016_auto_20180201_1642.py, django_project/base/models/project.py
Before:
```
WARNINGS:
base.Project.certification_manager: (fields.W340) null has no effect on ManyToManyField.
base.Project.changelog_manager: (fields.W340) null has no effect on ManyToManyField.
base.Project.lesson_manager: (fields.W340) null has no effect on ManyToManyField.
base.Project.sponsorship_manager: (fields.W340) null has no effect on ManyToManyField.
```
=> remove warnings in migration

django_project/changes/migrations/0010_auto_20180205_1046.py, django_project/changes/models/entry.py, django_project/changes/templates/entry/order.html, django_project/changes/templates/version/detail-content.html, django_project/changes/urls.py, django_project/changes/views/entry.py
Ticket #30 
I can still refactor the code later to avoid the copy/paste of the HTML template.
@timlinux @ann26 I need to check why I need to remove this variable from the context. I'm not sure about this middleware:
If I don't introduce this hack, I get:
```
Traceback:
File "/usr/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
157.                     response = middleware_method(request, response)
File "/home/web/django_project/core/custom_middleware.py" in process_template_response
98.             context['the_version'] = context.get('entry').version
Exception Type: AttributeError at /en/1/version/35/order/1
Exception Value: 'QuerySet' object has no attribute 'version'
```
I have a list of entry L98, so it's normal that `version` doesn't work on a …
=> re order entries within the same category

django_project/lesson/migrations/0016_curriculum_curriculumworksheets.py, django_project/lesson/models/__init__.py, django_project/lesson/models/curriculum.py, django_project/lesson/models/curriculum_worksheets.py
Add models for the curriculum
#740
=> add curriculum models

django_project/certification/migrations/0015_auto_20180207_0531.py, django_project/certification/migrations/0015_auto_20180207_1243.py, django_project/certification/models/course_type.py, django_project/certification/templates/course_type/detail.html
=> alter description length to be 1000 characters

django_project/certification/views/certificate.py
=> restrict regenerate certificate view

django_project/certification/views/certifying_organisation.py
fix #763 
This PR fixes duplicate pending certifying organisation queries when a user has multiple role within a project.
=> fix duplicate queries

django_project/base/templates/project/delete.html, django_project/changes/templates/category/delete.html, django_project/changes/templates/category/detail.html, django_project/changes/templates/category/order.html, django_project/changes/templates/entry/delete.html, django_project/changes/templates/entry/includes/entry_detail.html, django_project/changes/templates/sponsor/delete.html, django_project/changes/templates/sponsor/detail.html, django_project/changes/templates/sponsor/invoice.html, django_project/changes/templates/sponsor/list.html, django_project/changes/templates/sponsor/pending-list.html, django_project/changes/templates/sponsor/sponsor_cloud.html, django_project/changes/templates/sponsorship_level/delete.html, django_project/changes/templates/sponsorship_level/detail.html, django_project/changes/templates/sponsorship_level/list.html, django_project/changes/templates/sponsorship_period/detail.html, django_project/changes/templates/sponsorship_period/list.html, django_project/changes/templates/version/delete.html, django_project/changes/templates/version/detail-content.html, django_project/changes/templates/version/detail-thumbs.html, django_project/changes/templates/version/includes/version-list-detail.html, django_project/lesson/templates/question/delete.html, django_project/vota/templates/ballot/delete.html, django_project/vota/templates/committee/delete.html
In Pycharm, search and replace with regex:
From `\{\{ MEDIA_URL \}\}\{\{ (.*) \}\}` to `{{ $1.url }}`
I find this code better than a URL concatenation. I guess django is doing the URL smartly.
Following this blogpost http://staticfiles.productiondjango.com/blog/stop-using-static-url-in-templates/
=> use the `url` property instead of doing URL concatenation for media

django_project/certification/templates/certifying_organisation/detail.html
Fix #678 
Allow only certying organisation managers to access call to action
=> Allow only certifying organisation managers to access 'call to action'

django_project/base/models/project.py, django_project/base/templates/custom_domain/delete.html, django_project/base/templates/custom_domain/list.html, django_project/base/templates/custom_domain/update.html, django_project/base/templates/organisation/delete.html, django_project/base/templates/organisation/list.html, django_project/base/templates/organisation/update.html, django_project/base/urls.py, django_project/base/views/custom_domain.py, django_project/base/views/organisation.py, django_project/core/base_templates/includes/base-auth-nav-left.html
Partially fix #663 
This PR (number is based upon lists in #663):
Static & Gifs
- Delete view for organisation
- Delete view for custom domain
- Domain menu navigation view
for staff users:
for non staff users:
- Login on custom domain:
- Edit view for organisations:
- Edit view for custom domain:
- Default organisation is "Public"
=> add update and delete view

django_project/changes/views/entry.py, django_project/core/settings/prod.py
After adding/updating an entry in the changelog, a normal user will be redirected to the pending queue. We should add this method to redirect users when they don't have enough permissions to see the view.
=> fix redirection when not enough permissions to view a page

django_project/base/templatetags/custom_markup.py
I've tried the suggested function in #723 and it works.
Although, the PR solves the GFM issue, the remaining job before closing completely the issue would be to style tables as there are no borders or styles applied (screenshot can be misleading as I used a third party dev tools to highlight table and cells in red)
=> Add support for tables in markdown using extensions

django_project/certification/templates/attendee/upload_attendee_csv.html
Fix #753 
I have added a screen layout of an example view for the csv that we expect to be uploaded.
=> Show example layout for a CSV file.

django_project/certification/admin.py, django_project/certification/models/certifying_organisation.py, django_project/certification/utilities.py, django_project/certification/views/certifying_organisation.py
fix #769 
Slug was created based upon project name and certifying organisation name, since they are unique together. However because project name and certifying organisation name are case sensitive and slug is made case insensitive, sometimes there could be duplicates. 
Example in project QGIS, we can create: Test organisation and test Organisation. Both will have same slug: qgis-test-organisation.
This PR change the slug creation using only certifying organisation name, and check if there is already same slug in the database for certifying organisation. When there are duplicates, the `check_slug` function will increment the slug.
So, for earlier example when we already have an object with slug `qgis-test-organisation`, the second object will have slug `1-qgis-test-organisation`
When …
=> Fix slug duplicates

django_project/changes/views/category.py
Fix #803 
Reference : https://docs.djangoproject.com/en/1.8/ref/models/querysets/#django.db.models.query.QuerySet.distinct
> By default, a QuerySet will not eliminate duplicate rows. In practice, this is rarely a problem, because simple queries such as Blog.objects.all() don’t introduce the possibility of duplicate result rows. However, if your query spans multiple tables, it’s possible to get duplicate results when a QuerySet is evaluated. That’s when you’d use distinct().
=> Make sure the pending category query set give distinct values.

django_project/lesson/views/answer.py
Fix #797
It expects keywords arguments. `self.pk_url_kwarg == 'pk'`. So, for some reasons, it resolves it as `p=k`
=> Fix #797. Error 500: Editing Answers.

django_project/certification/admin.py, django_project/certification/forms.py, django_project/certification/templates/attendee/create.html, django_project/certification/templates/course/detail.html, django_project/certification/tests/test_attendee_views.py, django_project/certification/views/attendee.py
fix #556 
Add new attendee and automatically add the newly created attendee into course:
Only add new attendee:
Also changed icons in course details, because there are two identical icons for different purpose:
one was for uploading new attendee using csv file and the other one for paying unpaid certificate
I changed it into this:
=> register attendee and add it into course in the same screen

django_project/changes/templates/version/detail.html, django_project/changes/views/version.py
fix #826 
We needed to fix our new permission checks on the changelog entry detail too.
=> fix changelog entry detail permission

django_project/lesson/templates/worksheet/detail.html
=> Fix more about image error

django_project/base/templatetags/custom_markup.py, django_project/core/base_static/css/changelog.css
Due to #723 follow-up
For reviewing, see the options I've choose to use at https://getbootstrap.com/docs/4.0/content/tables/, in particular for "Striped rows" (maybe you may not want)
The transformation from markdown to table generate two `<tbody>` instead of a `<theader>` & a `<tbody>`. It's the why I've made a change in the CSS file too.
=> Update table style using Boostrap & a custom class for header

django_project/base/tests/__init__.py, django_project/base/tests/test_views.py, django_project/core/settings/__init__.py
=> Tests for creating multiple organisation.

django_project/lesson/templates/worksheet/detail.html
=> fix action buttons layout on lesson question.

django_project/base/forms.py, django_project/base/tests/test_views.py, django_project/base/views/project.py
fix #736 
Project is approved by default and redirect user to home after creation.
=> project approved by default

django_project/certification/models/course_convener.py, django_project/certification/views/certificate.py
fix #868 
This PR fixes:
- Error when printing using special characters
- Duplicate slug for course convener
Printed certificate that initially fails:
=> fix print bug and convener slug duplicates

django_project/certification/views/certificate.py
fix #868 
Fixes encoding for convener title and degree on certificate details page.
=> fix string encoding

README.md, django_project/lesson/templates/worksheet/detail.html
- Fix missing image URL in the template
- Add codecov badge
The bug was in this url : http://changelog.kartoza.com/en/inasafe/section/introduction-to-inasafe/detail/11/
=> Fix missing image

django_project/lesson/templates/worksheet/detail.html
fix #878
- The else condition checking for user permission to display action buttons on answer were closing inside the div wrapping the action buttons for an answer hence giving the wierd display because there was no condition to hide the action buttons outside the div wrapping them.
- moved the else condition to the end of the div wrapping th eaction buttons for an answer and also wrapped the **check you knowledge** section and the **further reading** section in their own divs so as to explicitely seperate the content.
=> Fix worksheet detail content display

django_project/core/custom_middleware.py, django_project/core/settings/project.py, django_project/core/tests/test_check_domain_middleware.py
- Made `changelog.kartoza.com` as default site: where we can register domain.
- If we want to only show projects that belongs to kartoza, we can do that by registering `changelog.kartoza.com` for Kartoza organisation. After that the site should only showing the projects that belongs to Kartoza.
=> tweak domain

deployment/docker/REQUIREMENTS.txt
```
/usr/local/lib/python2.7/site-packages/psycopg2/__init__.py:144: UserWarning:
The psycopg2 wheel package will be renamed from release 2.8; 
in order to keep installing from binary please use "pip install psycopg2-binary" instead.
For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
```
But from the website: https://pypi.python.org/pypi/psycopg2-binary
> The binary package is a practical choice for development and testing but in production it is advised to use the package built from sources.
So ?
=> remove Python warning about psycopg2

django_project/changes/templates/sponsorship_period/list.html
=> Sponsorship period changes

django_project/changes/forms.py
This PR fixes http://sentry.kartoza.com/sentry/projecta/issues/25/
It fixed the form to check the unique together relations `project` and `sponsor`
gif: when trying to add a new sponsor with the same name within a project
=> fix sponsor form to check unique fields

django_project/certification/admin.py, django_project/certification/migrations/0019_auto_20180420_1205.py, django_project/certification/models/certificate.py
This PR fixes this http://sentry.kartoza.com/sentry/projecta/issues/123/ and http://sentry.kartoza.com/sentry/projecta/issues/125/
It fixes the unique together, that has caused there were duplicates in certificate. 
We also need to delete one of this certificate in database `QGIS-125` or `QGIS-126`. They are duplicates. They have the same attendee and course. I checked it on the course details page the attendee is no longer there. Maybe they have deleted the course attendee but the certificate remains.
=> fix unique together

django_project/changes/feeds/sponsor.py
fix #904 
Item descriptions:
example result:
```
<div>
</div>
<p class="sponsor_body gold">
<span>Sponsorship level: Gold : 9000 EUR</span><br/>
<span>Sponsorship period: 21 June 2017 - 21 June 2018</span><br/>
<span>Amount sponsored: EUR 9000.00<span>
</p>
```
=> reshape item descriptions

django_project/certification/models/certificate.py
Fix sentry issue: http://sentry.kartoza.com/sentry/projecta/issues/147/
Previously the certificate ID is incremented by counting the number of certificate within a project. This causes a problem that is certificate ID duplicates when we removed existing certificates.
The new increment ID system is looking at the latest certificate ID then increment it.
Example case:
Current certificate id is `QGIS-135` (the number of certificates in QGIS project is 135). Then we removes certificate with id `QGIS-127`. Thus the number of certificates in QGIS project is 134 but the latest certificate ID is QGIS-135.
Using old increment ID system:
Since the number of certificates in QGIS is 134, the new certificate is QGIS-135 (cause duplicate ID).
e.g. using new increment ID system:
Since it looks at the …
=> fix increment certificate ID

django_project/changes/feeds/sponsor.py, django_project/changes/urls.py
Some textual fixes (plural 'sponsors')
Add 'past' in feed descriptions for past-sponsors
Changed from '_' to '-' in sponsor url's
@timlinux I forgot that we actually use atom feeds for all feeds in the project... And tested/created only the rss one.
And added some smaller fixes.
=> Add atom url (used by QGIS project), plus

django_project/changes/urls.py, django_project/changes/views/version.py
=> update template download rst with the new one

django_project/changes/templates/sponsor/list.html, django_project/changes/tests/test_rss_view.py
follow up for #931 and fix #936 
The past sponsor button:
This button is slightly different than the other rss buttons:
=> add button for past sponsor rss and add test

django_project/changes/forms.py, django_project/changes/tests/test_views.py
fix #949 
Automatically Resolve URLs to **http://www.somlink.com/** if link is **www.somelink.com** and leave 'as is' if it is already prefixed with a scheme.
=> Resolve incorrect URL

django_project/base/forms.py, django_project/base/migrations/0021_auto_20180702_0420.py, django_project/base/migrations/0022_auto_20180702_0420.py, django_project/base/models/project.py, django_project/base/static/js/custom-project-form.js, django_project/base/templates/project/create.html, django_project/base/templates/project/update.html, django_project/base/tests/model_factories.py, django_project/certification/tests/views/test_certificate_views.py, django_project/certification/views/certificate.py
fix #959 and fix #966 
This PR:
Form:
Regenerate existing certificate will change the name of project representative:
=> add project representative field

django_project/certification/templates/certifying_organisation/list.html
fix #947 
I added the sign up button and about certification icon. These two icons are available for public.
When non logged in user click on sign up button, it will redirect them to login page then after login they'll see the create a new certifying organisation form.
Public:
Logged in user:
=> add sign up button

django_project/changes/views/version.py
=> fix editing permissions for changelog managers

deployment/docker/REQUIREMENTS.txt, django_project/certification/admin.py, django_project/certification/api_views/__init__.py, django_project/certification/api_views/get_status.py, django_project/certification/api_views/update_status.py, django_project/certification/management/__init__.py, django_project/certification/management/commands/__init__.py, django_project/certification/management/commands/set_status_existing_organisation.py, django_project/certification/migrations/0021_auto_20190904_1205.py, django_project/certification/migrations/0022_auto_20190904_1205.py, django_project/certification/migrations/0023_auto_20190904_1523.py, django_project/certification/migrations/0024_historicalcertifyingorganisation.py, django_project/certification/models/certifying_organisation.py, django_project/certification/models/status.py, django_project/certification/templates/certifying_organisation/pending-list.html, django_project/certification/tests/model_factories.py, django_project/certification/tests/test_models.py, django_project/certification/tests/views/test_certifying_organisation_views.py, django_project/certification/urls.py, django_project/certification/views/certifying_organisation.py, django_project/core/custom_middleware.py, django_project/core/settings/base.py, django_project/core/settings/contrib.py
This PR:
Editing status and remarks
We can also approve the organisation from this form as long as we have approved status on the list
Status can be added/edited/removed from admin. 
The order number is the order that will be displayed in the form.
The Status has foreign key with project and it's name is unique within the project (name and project are unique together).
After updating the Status model in admin, we can see in front end.
=> add status and remarks for certification review process

django_project/base/templates/project/new_detail.html, django_project/changes/templates/sponsor/create.html, django_project/changes/templates/sponsor/delete.html, django_project/changes/templates/sponsor/detail.html, django_project/changes/templates/sponsor/list.html, django_project/changes/templates/sponsor/pending-list.html, django_project/changes/templates/sponsor/renewed.html, django_project/changes/templates/sponsor/sponsor_cloud.html, django_project/changes/templates/sponsor/update.html, django_project/changes/templates/sponsor/world-map.html, django_project/changes/templates/sponsorship_level/create.html, django_project/changes/templates/sponsorship_level/delete.html, django_project/changes/templates/sponsorship_level/detail.html, django_project/changes/templates/sponsorship_level/list.html, django_project/changes/templates/sponsorship_level/update.html, django_project/changes/templates/sponsorship_period/create.html, django_project/changes/templates/sponsorship_period/delete.html, django_project/changes/templates/sponsorship_period/detail.html, django_project/changes/templates/sponsorship_period/list.html, django_project/changes/templates/sponsorship_period/update.html, django_project/core/base_templates/includes/base-auth-nav-left.html
fix #1044 
Some wording change:
The sponsorship levels names were changed from the admin section.
=> change sponsor to sustaining member

deployment/docker/REQUIREMENTS.txt
fix #1047 and fix #1039 
Using the latest Pillow breaks the code when using reportlab for drawing image.
We need to explicitly install earlier version of Pillow in requirements. In this case `Pillow==5.3.0`
=> add pillow 5.3.0 in requirements

django_project/certification/forms.py, django_project/certification/templates/course/detail.html
fix #1031 
This PR:
Previously, we can issue certificates as many as we need regardless the amount of the available credits but we cannot print them when the credits are not sufficient, thus we can have negative credits. In the previous logic, once we have sufficient credits, we can pay the issued certificates but not printed using the credits.
=> only enable issue button when credits are sufficient

django_project/lesson/templates/section/includes/row-worksheet.html, django_project/lesson/templates/section/includes/section-list-detail.html, django_project/lesson/views/worksheet.py
fix #1076 
@timlinux @Gustry 
This PR:
=> fix lesson numbering

django_project/changes/admin.py, django_project/changes/models/version.py, django_project/changes/views/version.py
fix #1066 
This PR fixes the sorting on version list by fixing the numbering format of the version which will be used to compute the padded version.
=> fix version numbering for sorting

django_project/certification/templates/certifying_organisation/pending-list.html
fix #1079 
View for certifying organisation owner but not a staff or managers.
=> allow certifying organisation owner to edit and delete its own pending organisation

django_project/certification/views/certificate.py, django_project/changes/admin.py, django_project/changes/models/sponsorship_period.py, django_project/changes/templates/version/detail.html, django_project/changes/templates/version/includes/github-form-modal.html, django_project/changes/urls.py, django_project/changes/views/__init__.py, django_project/changes/views/changelog_github.py, django_project/core/settings/contrib.py
fix #1128 
This PR:
Note:
- On deployment we need github token so that we can have request to github API up until 5000 request per hour, without this token we only have 60 requests per hour 
- for rate limiting, see: https://developer.github.com/v3/#rate-limiting.
- to set up github token see: https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line#creating-a-token
1. Click on the github icon on the right side of the page, it will open a pop up to import the PRs.
2. The repository url is filled automatically but should you like to import the PR from another repository you can fill it here too (<b>required</b>).
3. Wait until the label options is rendered.
4. Select the label of which you want to import the PR, if you select more …
=> add function to import PR into entries

README.md, django_project/certification/views/certificate.py
fix #1043 
"Times-Italic" font does not support turkish characters, so I changed it to use the regular one, "Noto-Regular" is it okay @timlinux ?
before:
after:
=> change font to support turkish characters

django_project/certification/feeds/__init__.py, django_project/certification/feeds/course.py, django_project/certification/feeds/geojson_feed.py, django_project/certification/feeds/json_feed.py, django_project/certification/feeds/training_center.py, django_project/certification/models/certifying_organisation.py, django_project/certification/models/course.py, django_project/certification/models/training_center.py, django_project/certification/templates/certifying_organisation/detail.html, django_project/certification/templates/certifying_organisation/list.html, django_project/certification/urls.py
fix #1158 
I added buttons for links to training geojson feed, upcoming courses feed and past courses feed:
```json
{
"rss": {
"version": "2.0", 
"channel": {
"title": "GeoJSON Feed training center of Kartoza (Pty) Ltd", 
"description": "These are the training center of Kartoza (Pty) Ltd.", 
"link": "http://0.0.0.0:61202/en/qgis/certifyingorganisation/qgis-kartoza-pty-ltd/", 
"homepage": "https://kartoza.com", 
"lastBuildDate": "Thu, 05 Mar 2020 08:41:45 +0000", 
"item": [
{
"type": "Feature", 
"geometry": {
"type": "Point", 
"coordinates": [32.65, -0.15]
}, 
"properties": {
"name": "Uganda"
}
}, {
"type": "Feature", 
"geometry": {
"type": "Point", 
"coordinates": [11.6, 42.81]
}, 
"properties": {
"name": "Trieste ICTP"
}
}, {
"type": "Feature", 
"geometry": {
"type": "Point", …
```
=> add feed for training center and courses
